# Generated by Django 3.2.5 on 2021-08-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_image'),
        ('shop', '0004_invoice_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='media_app.image'),
        ),
        migrations.AlterField(
            model_name='productgalleryimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_gallery_images', to='media_app.image'),
        ),
    ]
